work_dir: ./ctr2d_loss/ctr_bone2d/work_dir
model_saved_name: ./ctr2d_loss/ctr_bone2d/runs

# feeder
dataset: datasets.dataset.UavDataset
train_data_args:
  data_path:
   /root/UAV/data/train_bone.npy
  label_path: /root/UAV/data/train_label.npy
  random_choose: True
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  debug: False
  use_mmap: True
  random_rot: False
  p_interval: [0.5, 1]
  d: 2

val_data_args:
  data_path:
   /root/UAV/data/val_bone.npy
  label_path: /root/UAV/data/val_label.npy
  debug: False
  window_size: 64
  p_interval: [ 0.95 ]
  d: 2

# model
model: model.ctrgcn_xy_loss.Model
model_args:
  num_class: 155
  num_point: 17
  num_person: 2
  graph: graph.uav.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0004
base_lr: 0.1
lr_decay_rate: 0.1
step: [35, 55]
warm_up_epoch: 5

# training
device: 0
batch_size: 32
test_batch_size: 64
num_epoch: 70
nesterov: True