pred_name: pred_td_fr_bone2d

# feeder
dataset: datasets.dataset.UavDataset
test_data_args:
  data_path: ./data_test/test_bone.npy
  debug: False
  window_size: 64
  p_interval: [ 0.95 ]
  is_test: True
  d: 2

# model
model: model.fr_tdgcn_xy.Model
model_args:
  num_class: 155
  num_point: 17
  num_person: 2
  graph: graph.uav.Graph
  graph_args:
    labeling_mode: 'spatial'

# test
phase: test
device: 0
test_batch_size: 128
weights: /root/UAV/td2d/td_bone2d/runs-60-15921.pt