work_dir: ./mixformerk290/mixformer_jm/work_dir
model_saved_name: ./mixformerk290/mixformer_jm/runs

# feeder
dataset: datasets.dataset.UavDataset
train_data_args:
  data_path:
   /root/UAV/data/train_joint_motion.npy
  label_path: /root/UAV/data/train_label.npy
  random_choose: True
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  debug: False
  use_mmap: True
  random_rot: False
  p_interval: [0.5, 1]
  d: 2

val_data_args:
  data_path:
   /root/UAV/data/val_joint_motion.npy
  label_path: /root/UAV/data/val_label.npy
  random_choose: True
  debug: False
  window_size: 64
  p_interval: [ 0.95 ]
  d: 2

# model
model: model.ske_mixfk2.Model
model_args:
  num_class: 155
  num_point: 17
  num_person: 2
  graph: graph.uav.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0005
base_lr: 0.2
#lr_decay_rate: 0.1
step: [35, 55,70]
warm_up_epoch: 5

# training
device: 0
batch_size: 64
test_batch_size: 128
num_epoch: 90
nesterov: True