pred_name: pred_ctr_fr_jb

# feeder
dataset: datasets.dataset.UavDataset
test_data_args:
  data_path: ./data_test/test_joint_bone.npy
  debug: False
  window_size: 64
  p_interval: [ 0.95 ]
  is_test: True

# model
model: model.fr_ctrgcn.Model
model_args:
  num_class: 155
  num_point: 17
  num_person: 2
  in_channels: 6
  graph: graph.uav.Graph
  graph_args:
    labeling_mode: 'spatial'

# test
phase: test
device: 0
test_batch_size: 128
weights: /root/UAV/ctr/ctr_jm/runs-61-16182.pt