pred_name: pred_ctr_fr_jm2d

# feeder
dataset: datasets.dataset.UavDataset
test_data_args:
  data_path: ./data_test/test_joint_motion.npy
  debug: False
  window_size: 64
  p_interval: [ 0.95 ]
  is_test: True
  d: 2

# model
model: model.fr_ctrgcn_xy.Model
model_args:
  num_class: 155
  num_point: 17
  num_person: 2
  graph: graph.uav.Graph
  graph_args:
    labeling_mode: 'spatial'

# test
phase: test
device: 0
test_batch_size: 128
weights: /root/UAV/ctr2d/ctr_jm2d/runs-61-16182.pt