pred_name: pred_ctr_fr_jb2d

# feeder
dataset: datasets.dataset.UavDataset
test_data_args:
  data_path: ./data_test/test_joint_bone.npy
  debug: False
  window_size: 64
  p_interval: [ 0.95 ]
  is_test: True
  d: 4

# model
model: model.fr_ctrgcn_xy.Model
model_args:
  num_class: 155
  num_point: 17
  num_person: 2
  in_channels: 4
  graph: graph.uav.Graph
  graph_args:
    labeling_mode: 'spatial'

# test
phase: test
device: 0
test_batch_size: 128
weights: /root/UAV/ctr2d/ctr_bm2d/runs-63-16704.pt