work_dir: ./te/te_joint/work_dir
model_saved_name: ./te/te_joint/runs

# feeder
dataset: datasets.dataset.UavDataset
train_data_args:
  data_path:
   /root/UAV/data/train_joint.npy
  label_path: /root/UAV/data/train_label.npy
  random_choose: True
  random_shift: False
  random_move: False
  window_size: 60
  normalization: False
  debug: False
  use_mmap: True
  random_rot: False
  p_interval: [0.5, 1]

val_data_args:
  data_path:
   /root/UAV/data/val_joint.npy
  label_path: /root/UAV/data/val_label.npy
  debug: False
  window_size: 60
  p_interval: [ 0.95 ]

# model
model: model.fr_tegcn.Model
model_args:
  num_class: 155
  num_point: 17
  num_person: 2
  graph: graph.uav.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0004
base_lr: 0.1
lr_decay_rate: 0.1
step: [35, 55]
warm_up_epoch: 5

# training
device: 0
batch_size: 64
test_batch_size: 128
num_epoch: 65
nesterov: True