work_dir: ./tdgcn_bone/work_dir
model_saved_name: ./tdgcn_bone/runs

# feeder
dataset: datasets.dataset.UavDataset
train_data_args:
  data_path:
   ./data/train_bone.npy
  label_path: ./data/train_label.npy
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  debug: False
  use_mmap: True
  random_rot: False
  p_interval: [0.5, 1]

val_data_args:
  data_path:
   ./data/test_A_bone.npy
  label_path: ./data/test_A_label.npy
  random_choose: False
  debug: False
  window_size: 64
  p_interval: [ 0.95 ]

# model
model: model.tdgcn.Model
model_args:
  num_class: 155
  num_point: 17
  num_person: 2
  graph: graph.uav.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0004
base_lr: 0.1
lr_decay_rate: 0.1
step: [35, 55]
warm_up_epoch: 5

# training
device: 0
batch_size: 16
test_batch_size: 32
num_epoch: 65
nesterov: True
