# feeder
dataset: datasets.dataset.UavDataset
test_data_args:
  data_path: ./data_test/test_B_joint.npy
  debug: False
  is_test: True

# model
model: model.fr_tegcn.Model
model_args:
  num_class: 155
  num_point: 17
  num_person: 2
  graph: graph.uav.Graph
  graph_args:
    labeling_mode: 'spatial'

# test
phase: test
device: 0
test_batch_size: 128
weights: ./tegcn_joint/runs/uav-63-32832.pt

# save_score: True
