pred_name: pred_td_jm

# feeder
dataset: datasets.dataset.UavDataset
test_data_args:
  data_path: ./data_test/test_joint_motion.npy
  debug: False
  window_size: 64
  p_interval: [ 0.95 ]
  is_test: True

# model
model: model.tdgcn.Model
model_args:
  num_class: 155
  num_point: 17
  num_person: 2
  graph: graph.uav.Graph
  graph_args:
    labeling_mode: 'spatial'

# test
phase: test
device: 0
test_batch_size: 128
weights: /root/UAV/td/td_jm/runs-58-15399.pt